// This is the home page [the first page that you see when the app starts]

import Head from 'next/head'     // similar to html head tag you can put the meta information,title etc here
import styles from '../styles/Home.module.css' //for naming styles sheets to pages/components please follow [name].module.css
// here we are importing styles for home page

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to Decodecafe</h1>
    </div>
  )
}
